### ISSUE TITLE
Add "debug_mode" and "color_enable" to the configuration description.

### ISSUE THREAD

**Issue by tenten0213** [sdkman/sdkman-website#28]
The following items are missing.
`sdkman_debug_mode` is very useful. So I would like you to add it.

```
sdkman_debug_mode=true|false
sdkman_colour_enable=true|false
```

https://github.com/sdkman/sdkman-website/blob/master/src/main/twirl/usage.scala.html
https://sdkman.io/usage#config

**Comment by marc0der** [comment]
Please follow the contributor guidelines (template of which you deleted) before opening an issue here.

**Comment by tenten0213** [comment]
OK. Where is contributor guidelines and template?

Is this? Is this a template for sdkman-cli?

* https://github.com/sdkman/sdkman-cli/blob/master/CONTRIBUTING.md
* https://github.com/sdkman/sdkman-cli/blob/master/ISSUE_TEMPLATE.md

**Comment by marc0der** [comment]
My apologies @tenten0213, I only saw this now and realised that you had opened this issue against the website, which does not have the contributor guidelines.

**Comment by marc0der** [comment]
That is done now. Please let me know if that seems okay.
