### ISSUE TITLE
Docs don't mention WLS on Windows

### ISSUE THREAD

**Issue by dsyer** [sdkman/sdkman-website#30]
The docs say that sdkman "requires Cygwin or MSYS+MinGW" on Windows. This isn't strictly true any more, and now that the Windows Subsystem for Linux is in the Microsoft app store, this is arguably the best option anyway. Works for me BTW with WLS Ubuntu.

**Comment by marc0der** [comment]
I need to do some work on the website so can possibly release it over the weekend. Would you be willing to write the section @dsyer?

**Comment by dsyer** [comment]
Sure. Where's the code?

**Comment by marc0der** [comment]
Thanks! It's over here: https://github.com/sdkman/sdkman-website/blob/master/app/views/install.scala.html

**Comment by marc0der** [comment]
This has been resolved so closing the issue. As always, thanks for your contributions.
