### ISSUE TITLE
Update the entries for the JDKs page

### ISSUE THREAD

**Issue by marc0der** [sdkman/sdkman-website#53]
This list seems a bit out of date atm and needs to be updated.

**Comment by tsaarni** [comment]
I'm not following the Java development too closely, so I got bit confused when looking for updates. Short investigation suggests that:
* Temurin versions `[version]-tem` are the OpenJDK HotSpot builds (previously `[version].hs-adpt`)
* Semeru versions `[version]-sem` are the OpenJDK OpenJ9 builds (previously `[version].j9-adpt`)

is this correct?

**Comment by marc0der** [comment]
@tsaarni I'm away on holiday right now, but I'll write a blog post about this as soon as I can. In the meanwhile, I'll update the website soon.

**Comment by marc0der** [comment]
Everything is now addressed with #54.
