### ISSUE TITLE
Wrong link to MinGW

### ISSUE THREAD

**Issue by tedyoung** [sdkman/sdkman-website#55]
(Not sure where to file this issue, couldn't find any of the text of the docs on any of the repositories, so apologies if I missed it.)

On the sdkman.io/install page, it says:

>The third solution is for Git users using the Git Bash for Windows environment. In order for this to work, the environment needs to be supplemented with MinGW to add the necessary toolchain to function.

The link to `MinGW` points to `http://www.mingw.org/` which looks like a domain taken over by scammers.

I'm guessing the correct link is `https://msys2.org` and that MinGW has been replaced by MSys2?

Regardless, the link should be removed or replaced with a working link.

**Comment by TheFlagCourier** [comment]
Just bumped into this myself. Https Everywhere outright blocks it. You can proceed, in which case you are redirected to a `www{NUM}.mingw.org` address, and uBlock origin shows it trying to run several scripts from `img1.wsimg.com` and Google AdSense.

If SDKMAN! doesn't go with the proposed `https://msys2.org`, a redirect to `https://osdn.net/projects/mingw/` should be appropriate.
