### ISSUE TITLE
SDKMAN jdks page should list Tencent Kona JDK

### ISSUE THREAD

**Issue by johnshajiang** [sdkman/sdkman-website#67]
SDKMAN already supports Tencent Kona JDK, like the below,

```
% sdk list java | grep kona
Tencent       |     | 17.0.7       | kona    |            | 17.0.7-kona
              |     | 11.0.19      | kona    |            | 11.0.19-kona
              |     | 8.0.372      | kona    |            | 8.0.372-kona
```

But the below page doesn't list this JDK yet.
https://sdkman.io/jdks

Could this page add Tencent Kona?
Or, should I do something for that?

**Comment by marc0der** [comment]
Hey @johnshajiang, feel free to raise a PR.

**Comment by johnshajiang** [comment]
Do I only need to add a vendor block into [jdks.conf]?

[jdks.conf]:
<https://github.com/johnshajiang/sdkman-website/blob/master/conf/jdks.conf>
