### ISSUE TITLE
Some images are missing

### ISSUE THREAD

**Issue by mtgto** [sdkman/sdkman-website#71]
- https://sdkman.io/assets/%20/img/city.png
  - Contains an obstacle space? https://github.com/sdkman/sdkman-website/blob/e0b148d2e6593f75ff523af4f462aef1d5a17155/app/views/index.scala.html#L96
- img of `Fork me on GitHub`
  - https://github.com/sdkman/sdkman-website/blob/e0b148d2e6593f75ff523af4f462aef1d5a17155/app/views/includes/forkme.scala.html#L4
  - `Invalid upstream response (403)` in my environment

**Comment by marc0der** [comment]
Hi @mtgto, thanks for letting me know! I'm pushing a new release shortly that fixes the first issue.
The second one might have something to do with your environment because the "fork me" image displays just fine for me wherever I've tried.

**Comment by mtgto** [comment]
@marc0der 

> The second one might have something to do with your environment because the "fork me" image displays just fine for me wherever I've tried.

I reproduced it in my browser and VPS environment now. My guess is that it is a difference in browser cache, cookies, etc.

Can you please make sure it reproduces in a private browser?
If not, please close this issue.

In my AWS VPS: (response header says `x-cache: MISS`)

```console
$ curl -I https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67
HTTP/2 502
cache-control: no-cache, no-store, private, must-revalidate
content-security-policy: default-src 'none'; img-src data:; style-src 'unsafe-inline'
content-type: text/plain; charset=utf-8
server: github-camo (1a298b14)
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
x-github-request-id: F7E2:129FF:58C5A0:64F581:65181920
accept-ranges: bytes
date: Sat, 30 Sep 2023 12:48:33 GMT
via: 1.1 varnish
x-served-by: cache-tyo11961-TYO
x-cache: MISS
x-cache-hits: 0
x-timer: S1696078113.017709,VS0,VE194
x-fastly-request-id: 9a2d99d1146034159fdc1829a0c41cd5ac7e43c8
timing-allow-origin: https://github.com
content-length: 32
```

**Comment by marc0der** [comment]
It works fine for me. BTW, this is an image hosted by GitHub so I don't have much control over it. If your problem persists, please raise it with them.
