### ISSUE TITLE
fork me img src gets 403

### ISSUE THREAD

**Issue by zach-betz-hln** [sdkman/sdkman-website#77]
## Summary

Hi there, I stumbled upon your site after reading this [article](https://www.morling.dev/blog/getting-started-with-java-development-2023/).

It seems the "fork me" github widget in the top right is returning a 403 when requesting the img src.

## Screenshots

Network request:

![Screenshot 2024-01-16 at 9 42 19 AM](https://github.com/sdkman/sdkman-website/assets/119352232/c2f5fecb-68cb-45cb-96c4-afb36b565cab)

UI element:

![Screenshot 2024-01-16 at 9 42 52 AM](https://github.com/sdkman/sdkman-website/assets/119352232/6158dffc-446d-4cc5-a6c4-8ecfb3d5f8df)

**Comment by marc0der** [comment]
Hi @zach-betz-hln, thanks for reporting this. The widget is provided by GitHub and works perfectly when I click through. Could it be that you are on a VPN that blocks certain URLs?

**Comment by zach-betz-hln** [comment]
Hi @marc0der - I tried on and off vpn, and in incognito mode. Same result.

I'm able to click the Ui element as well. It's just the [CSS ribbon](https://simonwhitaker.github.io/github-fork-ribbon-css/) is not displaying for me 🤷‍♂️ 

If this is working fine on your end, feel free to close.

**Comment by zach-betz-hln** [comment]
Out of curiosity, when you go to these urls, do you get the same results?

- 403 for https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67
- 403 for https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png

**Comment by zach-betz-hln** [comment]
Closing this issue as overcome by events.
Looks like the https://sdkman.io/ site got a design revamp 🙂
