### ISSUE TITLE
Missing scroll-margin for `#` links

### ISSUE THREAD

**Issue by felix-staud** [sdkman/sdkman-website#79]
When using a `#` link e.g. https://sdkman.io/sdks#maven it scrolls too far because it's not taking the height of the navigation into account. This can be fixed with the css attribute `scroll-margin` ([mdn doc](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin))
<img width="877" alt="image" src="https://github.com/sdkman/sdkman-website/assets/50131232/55a577f6-4a51-42e0-a679-b03f80ecc7ac">

**Comment by SvMak** [comment]
Must be fixed in PR #80
